//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicingSampleApp {
    
    public partial class WebUserControl1 {
        protected System.Web.UI.HtmlControls.HtmlInputCheckBox authentication;
        protected System.Web.UI.WebControls.Panel permissions;
        protected System.Web.UI.WebControls.TextBox accessToken;
        protected System.Web.UI.WebControls.TextBox tokenSecret;
    }
}
